## This is a solution to coursera R Programming course, programming 
## assignment 2.


## makeCacheMatrix stores functions to create/manipulate a matrix.
## It contains four functions:
## set: set the value of the vector
## get: get the value of the vector
## setmatrix: set the value of the inversed matrix
## getmatrix: get the value of the inversed matrix


makeCacheMatrix <- function(x = matrix()) {
	m <- NULL
	set <- function(y) {
		x <<- y
		m <<- NULL
	}
	get <- function() x
	setmatrix <- function(solve) m <<- solve
	getmatrix <- function() m
	list(set = set, get = get, setmatrix = setmatrix, getmatrix = getmatrix)
}


## cacheSolve makes inverse of the matrix generated by makeCacheMatrix
## and it gets the inversed matrix if it exists in cache already, 
## otherwise calculate it by calling setmatrix from makeCacheMatrix.
## The function will return the inverse of x.

cacheSolve <- function(x, ...) {
        m <- x$getmatrix()
        if(!is.null(m)) {
        	message("getting cached data")
        	return(m)
        }
        matrix <- x$get()
        m <- solve(matrix, ...)
        x$setmatrix(m)
        m
}
